name: Louis Barnett
favicon: null
layout_spectrum: 0.0131616
typography_spectrum: 0.145419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120a08'
    - '#fee7d7'
    - '#9d0102'
    - '#f05521'
    - '#80887d'
  brandStrength: 0.8125
  lightness: 0.7914894
  saturation: 0.5
  rhythmicContrast: 0.7702128
purpose: []
