layout_spectrum: 0.0131616
color:
  saturation: 0.7872341
  brandStrength: 0.778272
  lightness: 0.7914894
  rhythmicContrast: 0.7702128
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.145419
name: Louis Barnett
